/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package meetdirector;

import java.io.File;
import java.util.HashMap;

/**
 *
 * @author nhorman
 */
public class MeetEntriesImportDialog extends javax.swing.JDialog {

    private static MeetEntriesImportDialog myself = null;
    private FileImporter importer;
    
    /**
     * Creates new form MeetImportDialog
     */
    public MeetEntriesImportDialog(java.awt.Frame parent, boolean modal, File importfile) {
        super(parent, modal);
        initComponents();
        this.setTitle("Importing Meet Data");
        this.importer = new FileImporter(importfile, this.getTextOutputArea());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DismissButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ImportResultsText = new javax.swing.JTextArea();
        StartImportButton = new javax.swing.JButton();
        ImportOptionsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AddEventsCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meet Import Progress");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DismissButton.setText("Dismiss");
        DismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DismissButtonActionPerformed(evt);
            }
        });

        ImportResultsText.setEditable(false);
        ImportResultsText.setColumns(20);
        ImportResultsText.setRows(5);
        jScrollPane1.setViewportView(ImportResultsText);

        StartImportButton.setText("Start Import");
        StartImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartImportButtonActionPerformed(evt);
            }
        });

        ImportOptionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImportOptionsLabel.setText("Import Options");
        ImportOptionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddEventsCheckbox.setText("Add events from file");
        AddEventsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventsCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImportOptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddEventsCheckbox))
                        .addGap(234, 234, 234)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StartImportButton)
                            .addComponent(DismissButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(StartImportButton)
                            .addGap(18, 18, 18)
                            .addComponent(DismissButton))
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImportOptionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddEventsCheckbox)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DismissButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_DismissButtonActionPerformed

    private void AddEventsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventsCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEventsCheckboxActionPerformed

    private void StartImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartImportButtonActionPerformed
        //When pressed, apply the options to the importer and start the import
        HashMap options = importer.getOptions();
        options.put(FileImporter.IMPORT_NOT_FOUND_EVENTS, this.AddEventsCheckbox.isSelected());
        importer.setOptions(options);
        importer.ImportMeetEntryFile();
        this.DismissButton.setEnabled(true);
    }//GEN-LAST:event_StartImportButtonActionPerformed

    public javax.swing.JTextArea getTextOutputArea() {
        return this.ImportResultsText;
    }
    
    public void OpenWindow() {
        if (myself != null)
            return;
        myself = this;
        this.DismissButton.setEnabled(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                myself.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        return;
                    }
                });
                myself.setVisible(true);
                myself = null;
            }
        });
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AddEventsCheckbox;
    private javax.swing.JButton DismissButton;
    private javax.swing.JLabel ImportOptionsLabel;
    private javax.swing.JTextArea ImportResultsText;
    private javax.swing.JButton StartImportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
